# https://taskfile.dev

version: "3"

tasks:
  format:
    cmds:
      - uv run ruff format .
      - shfmt -i 2 -s -w .

  lint:
    cmds:
      - uv run ruff check .
      - shellcheck .

  compress:
    cmds:
      - uv run compress.py

  svg2pdf:
    cmds:
      - |
        ./scripts/svg2png.sh \
          ./files/input/image/svg \
          ./files/output/image/png \
          300
