# https://taskfile.dev

version: "3"

tasks:
  format:
    cmds:
      - uv run ruff format .

  lint:
    cmds:
      - uv run ruff check .
      - shellcheck .

  compress:
    cmds:
      - uv run compress.py
  
  svg2pdf:
    cmds:
      - |
        ./scripts/svg2pdf.sh \
          ./input/images/svg \
          ./output/images/png\
          500
