# https://taskfile.dev

version: "3"

tasks:
  install:
    cmds:
      - brew install pdf2svg librsvg

  format:
    cmds:
      - uv run ruff format .
      - shfmt -i 2 -s -w .

  lint:
    cmds:
      - uv run ruff check .
      - shellcheck .

  pdf2svg:
    cmds:
      - |
        ./scripts/pdf2svg.sh \
          ./files/drawing-pdfs \
          ./files/drawing-svgs

  svg2png:
    cmds:
      - |
        ./scripts/svg2png.sh \
          ./files/drawing-svgs \
          ./files/drawing-pngs \
          10000

  compress-images:
    cmds:
      - |
        uv run ./scripts/pdf_compress_images.py \
          ./files/input.pdf \
          ./files/output.pdf \
          200 \
          50

  compress:
    cmds:
      - |
        uv run ./scripts/pdf_compress.py \
          ./files/input.pdf \
          ./files/output.pdf \
          300 \
          78
